// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmveoecidsihvfmonpdn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptdmVvZWNpZHNpaHZmbW9ucGRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3OTE5MzksImV4cCI6MjA2MDM2NzkzOX0.xRb6TKXmti0F0ucSlJrVXmHDz7yK8csRgvAoG9sBdo0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);